### ISSUE TITLE
Plugin seems to ignore match words set to "all"

### ISSUE THREAD

**Issue by afrozl** [oplik0/nodebb-plugin-meilisearch#42]
The search function appears to ignore the distinction between match words being set to "any" or "all"

I was able to get the expected results by adding the following to plugin.search
```
     if (data.matchWords && data.matchWords === 'all') {
             data.content = data.content.split(" ").map(x => `"${x}"`).join(' ')
     }
```

**Comment by oplik0** [comment]
0.7.2 will have this fixed - though ultimately by using Meilisearch [matching strategy](https://www.meilisearch.com/docs/reference/api/search#matching-strategy) setting - since your version results in phrase searching by default (which is probably not what you want from your fuzzy search engine...)
